/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright held by the original author
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      controlDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

application     openFuelCell;

startFrom       startTime;

startTime       0;

stopAt          endTime;

// Fixed-current crossover experiment at 1 A/cm2.
endTime         20;

deltaT          0.1;

writeControl    runTime;

writeInterval   20;

purgeWrite      0;

writeFormat     ascii;

writePrecision  7;

writeCompression  off;

timeFormat      general;

timePrecision   6;

runTimeModifiable yes;

// ************************************************************************* //
