/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM
\*---------------------------------------------------------------------------*/

inline const Foam::volScalarField& Foam::hydrogenCrossoverModel::cH2() const
{
    return cH2_;
}


inline Foam::volScalarField& Foam::hydrogenCrossoverModel::cH2()
{
    return cH2_;
}


inline const Foam::volScalarField& Foam::hydrogenCrossoverModel::DH2Eff() const
{
    return DH2Eff_;
}


inline Foam::volScalarField& Foam::hydrogenCrossoverModel::DH2Eff()
{
    return DH2Eff_;
}


inline const Foam::volScalarField& Foam::hydrogenCrossoverModel::h2Dmdt() const
{
    return h2Dmdt_;
}


inline Foam::volScalarField& Foam::hydrogenCrossoverModel::h2Dmdt()
{
    return h2Dmdt_;
}


inline const Foam::volScalarField& Foam::hydrogenCrossoverModel::JH2Diff() const
{
    return JH2Diff_;
}


inline Foam::volScalarField& Foam::hydrogenCrossoverModel::JH2Diff()
{
    return JH2Diff_;
}


inline const Foam::volScalarField& Foam::hydrogenCrossoverModel::JH2Drag() const
{
    return JH2Drag_;
}


inline Foam::volScalarField& Foam::hydrogenCrossoverModel::JH2Drag()
{
    return JH2Drag_;
}

// ************************************************************************* //
